# Generated by Django 6.0 on 2026-01-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MockStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(max_length=255)),
                ('carrera', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MockFinancialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiene_deuda', models.BooleanField(default=False)),
                ('monto_deuda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_status', to='simulation.mockstudent')),
            ],
        ),
        migrations.CreateModel(
            name='MockAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(max_length=100)),
                ('nota', models.IntegerField()),
                ('semestre', models.CharField(max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='simulation.mockstudent')),
            ],
        ),
    ]
