# Generated by Django 6.0 on 2026-01-29 01:29

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Documento_Subido',
                'verbose_name_plural': 'Documentos_Subidos',
                'db_table': 'institucional_documentos',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_text', models.TextField()),
                ('chunk_index', models.IntegerField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='institutional.uploadeddocument')),
            ],
            options={
                'verbose_name': 'Fragmento_de_Documento',
                'verbose_name_plural': 'Fragmentos_de_Documentos',
                'db_table': 'institucional_fragmentos',
                'indexes': [pgvector.django.indexes.HnswIndex(fields=['embedding'], name='chunk_embedding_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
