# Generated by Django 6.0 on 2026-02-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='access_level',
            field=models.CharField(choices=[('public', 'Público (Todos)'), ('student', 'Solo Estudiantes'), ('teacher', 'Solo Docentes')], default='public', help_text='Quién puede ver este documento en el chat.', max_length=20),
        ),
    ]
