# Generated by Django 6.0 on 2026-02-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutional', '0002_uploadeddocument_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='access_level',
            field=models.CharField(choices=[('public', 'Público (Todos)'), ('student', 'Solo Estudiantes'), ('teacher', 'Solo Docentes'), ('admin', 'Solo Administrativos'), ('staff', 'Docentes y Administrativos')], default='public', help_text='Quién puede ver este documento en el chat.', max_length=20),
        ),
    ]
