# Generated by Django 6.0 on 2025-12-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=100)),
                ('semestre_actual', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MockGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='2024-1', max_length=20)),
                ('data', models.JSONField(default=dict, help_text="Formato: {'materia': nota, ...}")),
            ],
        ),
    ]
