# Generated by Django 6.0 on 2025-12-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de teléfono para integración con WhatsApp', max_length=20, null=True, unique=True),
        ),
    ]
